apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nginx:1.15.3-alpine
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        volumeMounts:
        - name: "config"
          mountPath: "/etc/nginx"
      volumes:
      - name: config
        configMap:
          name: nginx-conf

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;

    events {
      worker_connections 10;
    }

    http {
      access_log /dev/stdout;

      server {
        listen 80;
        listen [::]:80;
        server_name hello.blualism.com;
        location / {
          proxy_pass http://helloworld.default.svc.cluster.local:8080;
        }
      }
      server {
        listen 80;
        listen [::]:80;
        server_name httpbin.blualism.com;
        location / {
          proxy_pass http://httpbin.default.svc.cluster.local:8080;
        }
      }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.blualism.com"

spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress