---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: httpbin
  name: traefik-ingress-controller

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: httpbin

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect-scheme
  namespace: httpbin
spec:
  redirectScheme:
    scheme: https
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: httpbin
  name: httpbin
  labels:
    app: httpbin

spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: docker.io/kennethreitz/httpbin
          ports:
            - name: web
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: httpbin
---
  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: httpbin
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`httpbin.blualism.com`)
    kind: Rule
    services:
    - name: httpbin
      port: 80
    middlewares:
      - name: https-redirect-scheme
        namespace: httpbin

  tls:
    certResolver: default
---
